package com.bookie.integrations.venmo;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import org.junit.jupiter.api.Test;

class VenmoCsvInputAdapterTest {

  private final VenmoCsvInputAdapter adapter = new VenmoCsvInputAdapter();

  @Test
  void parsesTheTransactionSectionAfterStatementPreamble() throws Exception {
    String csv =
        """
        Account Statement
        Generated by Venmo
        ,ID,Datetime,Type,Status,Note,From,To,Amount (total)
        ,tx-1,2026-01-03T09:15:00,Payment,Complete,January rent,@alice,Demo User,"+ $1,200.00"
        """;

    VenmoStatement result = adapter.parse(csv.getBytes(StandardCharsets.UTF_8));

    assertThat(result.totalRows()).isEqualTo(1);
    assertThat(result.invalidRows()).isZero();
    assertThat(result.transactions()).singleElement();
    assertThat(result.transactions().getFirst())
        .isEqualTo(
            new VenmoTransaction(
                "tx-1",
                "@alice",
                new BigDecimal("1200.00"),
                LocalDate.of(2026, 1, 3),
                "Venmo - January rent"));
  }

  @Test
  void countsMalformedRowsWithoutDiscardingValidTransactions() throws Exception {
    String csv =
        """
        ,ID,Datetime,Type,Status,Note,From,To,Amount (total)
        ,bad-1,,Payment,Complete,Missing date,@alice,Demo User,+ $10.00
        ,good-1,2026-04-05,Payment,Complete,,@bob,Demo User,($25.00)
        """;

    VenmoStatement result = adapter.parse(csv.getBytes(StandardCharsets.UTF_8));

    assertThat(result.totalRows()).isEqualTo(2);
    assertThat(result.invalidRows()).isEqualTo(1);
    assertThat(result.transactions().getFirst().amount()).isEqualByComparingTo("-25.00");
    assertThat(result.transactions().getFirst().description()).isEqualTo("Venmo payment from bob");
  }

  @Test
  void rejectsInputsWithoutAVenmoTransactionHeader() {
    assertThatThrownBy(
            () -> adapter.parse("not,a,venmo,statement".getBytes(StandardCharsets.UTF_8)))
        .isInstanceOf(VenmoInputException.class)
        .hasMessageContaining("header row");
  }
}
