SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM financial_categories
WHERE system = TRUE
  AND category_key NOT IN (
      'RENTAL_INCOME',
      'ADVERTISING',
      'AUTO_AND_TRAVEL',
      'CLEANING_AND_MAINTENANCE',
      'COMMISSIONS',
      'INSURANCE',
      'LEGAL_AND_PROFESSIONAL',
      'MANAGEMENT_FEES',
      'MORTGAGE_INTEREST',
      'OTHER_INTEREST',
      'REPAIRS',
      'SUPPLIES',
      'TAXES',
      'UTILITIES',
      'DEPRECIATION',
      'OTHER',
      'WAGES',
      'REIMBURSEMENT',
      'EDUCATOR_EXPENSE',
      'EMPLOYMENT_OTHER_EXPENSE',
      'SERVICE_INCOME',
      'SCHEDULE_C_ADVERTISING',
      'SCHEDULE_C_CAR_AND_TRUCK',
      'SCHEDULE_C_CONTRACT_LABOR',
      'SCHEDULE_C_INSURANCE',
      'SCHEDULE_C_LEGAL_AND_PROFESSIONAL',
      'SCHEDULE_C_OFFICE_EXPENSE',
      'SCHEDULE_C_REPAIRS',
      'SCHEDULE_C_SUPPLIES',
      'SCHEDULE_C_UTILITIES',
      'SCHEDULE_C_OTHER_EXPENSE',
      'OTHER_INCOME',
      'OTHER_REIMBURSEMENT',
      'OTHER_EXPENSE'
  );

CREATE TABLE reporting_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_key VARCHAR(50) NOT NULL,
    label VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_reporting_profiles_key UNIQUE (profile_key)
);

INSERT INTO reporting_profiles (profile_key, label, active)
VALUES
    ('SCHEDULE_E', 'Schedule E', TRUE),
    ('SCHEDULE_C', 'Schedule C', TRUE),
    ('W2', 'W-2 employment', TRUE),
    ('NONE', 'No tax report', TRUE);

CREATE TABLE neutral_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_key VARCHAR(100) NOT NULL,
    label VARCHAR(255) NOT NULL,
    direction VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    system BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_neutral_categories_key UNIQUE (category_key)
);

INSERT INTO neutral_categories (category_key, label, direction, active, system)
SELECT
    CASE
        WHEN fc.category_key = 'REPAIRS' THEN 'REPAIRS_AND_MAINTENANCE'
        ELSE fc.category_key
    END,
    CASE
        WHEN fc.category_key = 'REPAIRS' THEN 'Repairs and maintenance'
        ELSE fc.label
    END,
    fc.direction,
    fc.active,
    TRUE
FROM financial_categories fc
WHERE fc.system = TRUE
  AND fc.category_key NOT IN (
      'SCHEDULE_C_ADVERTISING',
      'SCHEDULE_C_INSURANCE',
      'SCHEDULE_C_LEGAL_AND_PROFESSIONAL',
      'SCHEDULE_C_REPAIRS',
      'SCHEDULE_C_SUPPLIES',
      'SCHEDULE_C_UTILITIES',
      'OTHER',
      'SCHEDULE_C_OTHER_EXPENSE',
      'OTHER_REIMBURSEMENT'
  );

INSERT INTO neutral_categories (category_key, label, direction, active, system)
SELECT category_key, label, direction, active, FALSE
FROM financial_categories
WHERE system = FALSE;

CREATE TABLE legacy_category_map (
    legacy_category_id BIGINT PRIMARY KEY,
    neutral_category_id BIGINT NOT NULL,
    legacy_category_key VARCHAR(100) NOT NULL,
    CONSTRAINT uk_legacy_category_map_key UNIQUE (legacy_category_key),
    CONSTRAINT fk_legacy_category_map_legacy
        FOREIGN KEY (legacy_category_id) REFERENCES financial_categories(id),
    CONSTRAINT fk_legacy_category_map_neutral
        FOREIGN KEY (neutral_category_id) REFERENCES neutral_categories(id)
);

INSERT INTO legacy_category_map
    (legacy_category_id, neutral_category_id, legacy_category_key)
SELECT
    fc.id,
    nc.id,
    fc.category_key
FROM financial_categories fc
JOIN neutral_categories nc
  ON nc.category_key = CASE
      WHEN fc.system = FALSE THEN fc.category_key
      WHEN fc.category_key IN ('ADVERTISING', 'SCHEDULE_C_ADVERTISING')
          THEN 'ADVERTISING'
      WHEN fc.category_key IN ('INSURANCE', 'SCHEDULE_C_INSURANCE')
          THEN 'INSURANCE'
      WHEN fc.category_key IN (
          'LEGAL_AND_PROFESSIONAL',
          'SCHEDULE_C_LEGAL_AND_PROFESSIONAL'
      ) THEN 'LEGAL_AND_PROFESSIONAL'
      WHEN fc.category_key IN ('REPAIRS', 'SCHEDULE_C_REPAIRS')
          THEN 'REPAIRS_AND_MAINTENANCE'
      WHEN fc.category_key IN ('SUPPLIES', 'SCHEDULE_C_SUPPLIES')
          THEN 'SUPPLIES'
      WHEN fc.category_key IN ('UTILITIES', 'SCHEDULE_C_UTILITIES')
          THEN 'UTILITIES'
      WHEN fc.category_key IN ('OTHER', 'SCHEDULE_C_OTHER_EXPENSE', 'OTHER_EXPENSE')
          THEN 'OTHER_EXPENSE'
      WHEN fc.category_key IN ('REIMBURSEMENT', 'OTHER_REIMBURSEMENT')
          THEN 'REIMBURSEMENT'
      ELSE fc.category_key
  END;

CREATE TABLE activity_reporting_profile_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT NOT NULL,
    reporting_profile_id BIGINT NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    open_activity_id BIGINT GENERATED ALWAYS AS (
        CASE WHEN effective_to IS NULL THEN activity_id ELSE NULL END
    ),
    CONSTRAINT ck_activity_reporting_profile_range
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT uk_activity_reporting_profile_start
        UNIQUE (activity_id, effective_from),
    CONSTRAINT uk_activity_reporting_profile_open
        UNIQUE (open_activity_id),
    CONSTRAINT fk_activity_reporting_profile_activity
        FOREIGN KEY (activity_id) REFERENCES financial_activities(id) ON DELETE CASCADE,
    CONSTRAINT fk_activity_reporting_profile_profile
        FOREIGN KEY (reporting_profile_id) REFERENCES reporting_profiles(id)
);

INSERT INTO activity_reporting_profile_assignments
    (activity_id, reporting_profile_id, effective_from, effective_to)
SELECT fa.id, rp.id, DATE '0001-01-01', NULL
FROM financial_activities fa
JOIN reporting_profiles rp ON rp.profile_key = fa.tax_treatment;

CREATE TABLE category_reporting_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    neutral_category_id BIGINT NOT NULL,
    reporting_profile_id BIGINT NOT NULL,
    legacy_category_id BIGINT NOT NULL,
    report_line VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_category_reporting_mapping_policy
        UNIQUE (neutral_category_id, reporting_profile_id),
    CONSTRAINT uk_category_reporting_mapping_legacy
        UNIQUE (legacy_category_id),
    CONSTRAINT fk_category_reporting_mapping_neutral
        FOREIGN KEY (neutral_category_id) REFERENCES neutral_categories(id),
    CONSTRAINT fk_category_reporting_mapping_profile
        FOREIGN KEY (reporting_profile_id) REFERENCES reporting_profiles(id),
    CONSTRAINT fk_category_reporting_mapping_legacy
        FOREIGN KEY (legacy_category_id) REFERENCES financial_categories(id)
);

INSERT INTO category_reporting_mappings
    (
        neutral_category_id,
        reporting_profile_id,
        legacy_category_id,
        report_line,
        active
    )
SELECT
    lcm.neutral_category_id,
    rp.id,
    fc.id,
    fc.tax_line,
    fc.active
FROM financial_categories fc
JOIN legacy_category_map lcm ON lcm.legacy_category_id = fc.id
JOIN reporting_profiles rp ON rp.profile_key = fc.tax_treatment;

SELECT 1 / CASE WHEN
    (SELECT COUNT(*) FROM legacy_category_map)
        = (SELECT COUNT(*) FROM financial_categories)
    AND (SELECT COUNT(*) FROM category_reporting_mappings)
        = (SELECT COUNT(*) FROM financial_categories)
    AND (SELECT COUNT(*) FROM neutral_categories)
        = (SELECT COUNT(DISTINCT neutral_category_id) FROM legacy_category_map)
    AND (SELECT COUNT(*) FROM activity_reporting_profile_assignments)
        = (SELECT COUNT(*) FROM financial_activities)
THEN 1 ELSE 0 END;

SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM category_reporting_mappings mapping
JOIN financial_categories legacy_category
  ON legacy_category.id = mapping.legacy_category_id
JOIN reporting_profiles profile
  ON profile.id = mapping.reporting_profile_id
WHERE profile.profile_key <> legacy_category.tax_treatment
   OR mapping.report_line IS DISTINCT FROM legacy_category.tax_line
   OR mapping.active <> legacy_category.active;

SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM activity_reporting_profile_assignments assignment
JOIN financial_activities activity
  ON activity.id = assignment.activity_id
JOIN reporting_profiles profile
  ON profile.id = assignment.reporting_profile_id
WHERE profile.profile_key <> activity.tax_treatment
   OR assignment.effective_from <> DATE '0001-01-01'
   OR assignment.effective_to IS NOT NULL;

CREATE INDEX idx_activity_reporting_profile_effective
    ON activity_reporting_profile_assignments(activity_id, effective_from, effective_to);
CREATE INDEX idx_legacy_category_map_neutral
    ON legacy_category_map(neutral_category_id);
CREATE INDEX idx_category_reporting_mapping_profile
    ON category_reporting_mappings(reporting_profile_id, neutral_category_id);

CREATE TRIGGER enforce_activity_reporting_profile_non_overlap
BEFORE INSERT, UPDATE ON activity_reporting_profile_assignments
FOR EACH ROW
CALL 'com.bookie.catalog.reportpolicy.infrastructure.NonOverlappingReportingProfileAssignmentTrigger';
