-- Fail closed before creating the unified ledger. The migration copies every legacy financial
-- record; it never repairs, merges, or drops source rows.
SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM (
    SELECT id
    FROM incomes
    WHERE amount IS NULL
       OR amount <= 0
       OR date IS NULL
       OR description IS NULL
       OR activity_id IS NULL
       OR category_id IS NULL
    UNION ALL
    SELECT id
    FROM expenses
    WHERE amount IS NULL
       OR amount <= 0
       OR date IS NULL
       OR description IS NULL
       OR activity_id IS NULL
       OR category_id IS NULL
) invalid_financial_row;

SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM (
    SELECT i.id
    FROM incomes i
    LEFT JOIN financial_activities activity ON activity.id = i.activity_id
    LEFT JOIN financial_categories category ON category.id = i.category_id
    LEFT JOIN legacy_category_map category_map
      ON category_map.legacy_category_id = i.category_id
    LEFT JOIN legacy_payer_map payer_map ON payer_map.payer_id = i.payer_id
    WHERE activity.id IS NULL
       OR category.id IS NULL
       OR category.direction <> 'INCOME'
       OR category_map.legacy_category_id IS NULL
       OR (i.payer_id IS NOT NULL AND payer_map.payer_id IS NULL)
       OR i.property_id IS DISTINCT FROM activity.property_id
    UNION ALL
    SELECT e.id
    FROM expenses e
    LEFT JOIN financial_activities activity ON activity.id = e.activity_id
    LEFT JOIN financial_categories category ON category.id = e.category_id
    LEFT JOIN legacy_category_map category_map
      ON category_map.legacy_category_id = e.category_id
    LEFT JOIN legacy_payer_map payer_map ON payer_map.payer_id = e.payer_id
    WHERE activity.id IS NULL
       OR category.id IS NULL
       OR category.direction <> 'EXPENSE'
       OR category_map.legacy_category_id IS NULL
       OR (e.payer_id IS NOT NULL AND payer_map.payer_id IS NULL)
       OR e.property_id IS DISTINCT FROM activity.property_id
) unmappable_financial_row;

SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM (
    SELECT normalized_source.origin, normalized_source.external_id
    FROM (
        SELECT
            COALESCE(CAST(source_type AS VARCHAR), 'MANUAL') AS origin,
            source_id AS external_id
        FROM incomes
        WHERE source_id IS NOT NULL
        UNION ALL
        SELECT
            COALESCE(CAST(source_type AS VARCHAR), 'MANUAL') AS origin,
            source_id AS external_id
        FROM expenses
        WHERE source_id IS NOT NULL
    ) normalized_source
    GROUP BY normalized_source.origin, normalized_source.external_id
    HAVING COUNT(*) > 1
) duplicate_source_identity;

SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM (
    SELECT receipt_one_drive_id
    FROM (
        SELECT receipt_one_drive_id FROM incomes
        UNION ALL
        SELECT receipt_one_drive_id FROM expenses
    ) receipt_identity
    WHERE receipt_one_drive_id IS NOT NULL
    GROUP BY receipt_one_drive_id
    HAVING COUNT(*) > 1
) duplicate_attachment_identity;

CREATE TABLE financial_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(38, 2) NOT NULL,
    direction ENUM('INCOME', 'EXPENSE') NOT NULL,
    transaction_date DATE NOT NULL,
    description VARCHAR(2000) NOT NULL,
    activity_id BIGINT NOT NULL,
    neutral_category_id BIGINT NOT NULL,
    counterparty_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMP(6),
    migration_legacy_table VARCHAR(20),
    migration_legacy_id BIGINT,
    CONSTRAINT ck_financial_transactions_amount CHECK (amount > 0),
    CONSTRAINT uk_financial_transactions_migration_source
        UNIQUE (migration_legacy_table, migration_legacy_id),
    CONSTRAINT fk_financial_transactions_activity
        FOREIGN KEY (activity_id) REFERENCES financial_activities(id),
    CONSTRAINT fk_financial_transactions_neutral_category
        FOREIGN KEY (neutral_category_id) REFERENCES neutral_categories(id),
    CONSTRAINT fk_financial_transactions_counterparty
        FOREIGN KEY (counterparty_id) REFERENCES counterparties(id)
);

CREATE TABLE transaction_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    storage_provider VARCHAR(50) NOT NULL,
    external_id VARCHAR(255),
    file_name VARCHAR(500),
    sha256 VARCHAR(64),
    CONSTRAINT ck_transaction_attachments_identity
        CHECK (external_id IS NOT NULL OR file_name IS NOT NULL OR sha256 IS NOT NULL),
    CONSTRAINT uk_transaction_attachments_external
        UNIQUE (storage_provider, external_id),
    CONSTRAINT fk_transaction_attachments_transaction
        FOREIGN KEY (transaction_id) REFERENCES financial_transactions(id)
);

CREATE TABLE transaction_import_references (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    origin VARCHAR(50) NOT NULL,
    external_id VARCHAR(255),
    source_label VARCHAR(500),
    CONSTRAINT uk_transaction_import_references_external
        UNIQUE (origin, external_id),
    CONSTRAINT fk_transaction_import_references_transaction
        FOREIGN KEY (transaction_id) REFERENCES financial_transactions(id)
);

CREATE TABLE legacy_transaction_map (
    legacy_table ENUM('INCOMES', 'EXPENSES') NOT NULL,
    legacy_id BIGINT NOT NULL,
    transaction_id BIGINT NOT NULL,
    legacy_expense_category ENUM(
        'ADVERTISING',
        'AUTO_AND_TRAVEL',
        'CLEANING_AND_MAINTENANCE',
        'COMMISSIONS',
        'DEPRECIATION',
        'INSURANCE',
        'LEGAL_AND_PROFESSIONAL',
        'MANAGEMENT_FEES',
        'MORTGAGE_INTEREST',
        'OTHER',
        'OTHER_INTEREST',
        'REPAIRS',
        'SUPPLIES',
        'TAXES',
        'UTILITIES'
    ),
    canonical_hash VARCHAR(64) NOT NULL,
    mapped_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_legacy_transaction_map PRIMARY KEY (legacy_table, legacy_id),
    CONSTRAINT uk_legacy_transaction_map_transaction UNIQUE (transaction_id),
    CONSTRAINT ck_legacy_transaction_map_expense_category
        CHECK (legacy_table = 'EXPENSES' OR legacy_expense_category IS NULL),
    CONSTRAINT ck_legacy_transaction_map_hash
        CHECK (CHAR_LENGTH(canonical_hash) = 64),
    CONSTRAINT fk_legacy_transaction_map_transaction
        FOREIGN KEY (transaction_id) REFERENCES financial_transactions(id)
);

CREATE TABLE ledger_migration_quarantine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_table VARCHAR(20) NOT NULL,
    legacy_id BIGINT NOT NULL,
    reason VARCHAR(100) NOT NULL,
    salted_identity_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ledger_migration_quarantine_legacy
        UNIQUE (legacy_table, legacy_id),
    CONSTRAINT ck_ledger_migration_quarantine_hash
        CHECK (CHAR_LENGTH(salted_identity_hash) = 64)
);

INSERT INTO financial_transactions (
    amount,
    direction,
    transaction_date,
    description,
    activity_id,
    neutral_category_id,
    counterparty_id,
    created_at,
    updated_at,
    version,
    migration_legacy_table,
    migration_legacy_id
)
SELECT
    income.amount,
    'INCOME',
    income.date,
    income.description,
    income.activity_id,
    category_map.neutral_category_id,
    payer_map.counterparty_id,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0,
    'INCOMES',
    income.id
FROM incomes income
JOIN legacy_category_map category_map
  ON category_map.legacy_category_id = income.category_id
LEFT JOIN legacy_payer_map payer_map ON payer_map.payer_id = income.payer_id;

INSERT INTO financial_transactions (
    amount,
    direction,
    transaction_date,
    description,
    activity_id,
    neutral_category_id,
    counterparty_id,
    created_at,
    updated_at,
    version,
    migration_legacy_table,
    migration_legacy_id
)
SELECT
    expense.amount,
    'EXPENSE',
    expense.date,
    expense.description,
    expense.activity_id,
    category_map.neutral_category_id,
    payer_map.counterparty_id,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0,
    'EXPENSES',
    expense.id
FROM expenses expense
JOIN legacy_category_map category_map
  ON category_map.legacy_category_id = expense.category_id
LEFT JOIN legacy_payer_map payer_map ON payer_map.payer_id = expense.payer_id;

INSERT INTO transaction_import_references (
    transaction_id,
    origin,
    external_id,
    source_label
)
SELECT
    transaction.id,
    COALESCE(CAST(income.source_type AS VARCHAR), 'MANUAL'),
    income.source_id,
    income.source
FROM financial_transactions transaction
JOIN incomes income
  ON transaction.migration_legacy_table = 'INCOMES'
 AND transaction.migration_legacy_id = income.id
WHERE income.source_type IS NOT NULL
   OR income.source_id IS NOT NULL
   OR income.source IS NOT NULL;

INSERT INTO transaction_import_references (
    transaction_id,
    origin,
    external_id,
    source_label
)
SELECT
    transaction.id,
    COALESCE(CAST(expense.source_type AS VARCHAR), 'MANUAL'),
    expense.source_id,
    NULL
FROM financial_transactions transaction
JOIN expenses expense
  ON transaction.migration_legacy_table = 'EXPENSES'
 AND transaction.migration_legacy_id = expense.id
WHERE expense.source_type IS NOT NULL
   OR expense.source_id IS NOT NULL;

INSERT INTO transaction_attachments (
    transaction_id,
    storage_provider,
    external_id,
    file_name,
    sha256
)
SELECT
    transaction.id,
    'ONEDRIVE',
    income.receipt_one_drive_id,
    income.receipt_file_name,
    NULL
FROM financial_transactions transaction
JOIN incomes income
  ON transaction.migration_legacy_table = 'INCOMES'
 AND transaction.migration_legacy_id = income.id
WHERE income.receipt_one_drive_id IS NOT NULL
   OR income.receipt_file_name IS NOT NULL;

INSERT INTO transaction_attachments (
    transaction_id,
    storage_provider,
    external_id,
    file_name,
    sha256
)
SELECT
    transaction.id,
    'ONEDRIVE',
    expense.receipt_one_drive_id,
    expense.receipt_file_name,
    NULL
FROM financial_transactions transaction
JOIN expenses expense
  ON transaction.migration_legacy_table = 'EXPENSES'
 AND transaction.migration_legacy_id = expense.id
WHERE expense.receipt_one_drive_id IS NOT NULL
   OR expense.receipt_file_name IS NOT NULL;

INSERT INTO legacy_transaction_map (
    legacy_table,
    legacy_id,
    transaction_id,
    legacy_expense_category,
    canonical_hash,
    mapped_at
)
SELECT
    transaction.migration_legacy_table,
    transaction.migration_legacy_id,
    transaction.id,
    legacy_expense.category,
    LOWER(
        RAWTOHEX(
            HASH(
                'SHA-256',
                STRINGTOUTF8(
                    'v2|' || transaction.migration_legacy_table
                    || '|' || CAST(transaction.migration_legacy_id AS VARCHAR)
                    || '|' || transaction.direction
                    || '|' || CAST(transaction.amount AS VARCHAR)
                    || '|' || CAST(transaction.transaction_date AS VARCHAR)
                    || '|' || CAST(CHAR_LENGTH(transaction.description) AS VARCHAR)
                    || ':' || transaction.description
                    || '|' || CAST(transaction.activity_id AS VARCHAR)
                    || '|' || CAST(transaction.neutral_category_id AS VARCHAR)
                    || '|' || COALESCE(CAST(transaction.counterparty_id AS VARCHAR), '')
                    || '|' || COALESCE(CAST(legacy_expense.category AS VARCHAR), '')
                    || '|' || COALESCE(import_reference.origin, '')
                    || '|' || CAST(CHAR_LENGTH(COALESCE(import_reference.external_id, '')) AS VARCHAR)
                    || ':' || COALESCE(import_reference.external_id, '')
                    || '|' || CAST(CHAR_LENGTH(COALESCE(import_reference.source_label, '')) AS VARCHAR)
                    || ':' || COALESCE(import_reference.source_label, '')
                    || '|' || COALESCE(attachment.storage_provider, '')
                    || '|' || CAST(CHAR_LENGTH(COALESCE(attachment.external_id, '')) AS VARCHAR)
                    || ':' || COALESCE(attachment.external_id, '')
                    || '|' || CAST(CHAR_LENGTH(COALESCE(attachment.file_name, '')) AS VARCHAR)
                    || ':' || COALESCE(attachment.file_name, '')
                    || '|' || COALESCE(attachment.sha256, '')
                )
            )
        )
    ),
    CURRENT_TIMESTAMP
FROM financial_transactions transaction
LEFT JOIN expenses legacy_expense
  ON transaction.migration_legacy_table = 'EXPENSES'
 AND transaction.migration_legacy_id = legacy_expense.id
LEFT JOIN transaction_import_references import_reference
  ON import_reference.transaction_id = transaction.id
LEFT JOIN transaction_attachments attachment
  ON attachment.transaction_id = transaction.id;

-- Every legacy row must have exactly one target and one durable mapping, with exact grouped totals.
SELECT 1 / CASE WHEN
    (SELECT COUNT(*) FROM financial_transactions)
        = (SELECT COUNT(*) FROM incomes) + (SELECT COUNT(*) FROM expenses)
    AND (SELECT COUNT(*) FROM legacy_transaction_map)
        = (SELECT COUNT(*) FROM incomes) + (SELECT COUNT(*) FROM expenses)
    AND (SELECT COUNT(*) FROM ledger_migration_quarantine) = 0
    AND (
        SELECT COALESCE(SUM(amount), 0)
        FROM financial_transactions
        WHERE direction = 'INCOME'
    ) = (SELECT COALESCE(SUM(amount), 0) FROM incomes)
    AND (
        SELECT COALESCE(SUM(amount), 0)
        FROM financial_transactions
        WHERE direction = 'EXPENSE'
    ) = (SELECT COALESCE(SUM(amount), 0) FROM expenses)
THEN 1 ELSE 0 END;

SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM (
    SELECT income.id
    FROM incomes income
    LEFT JOIN legacy_transaction_map legacy_map
      ON legacy_map.legacy_table = 'INCOMES'
     AND legacy_map.legacy_id = income.id
    WHERE legacy_map.transaction_id IS NULL
    UNION ALL
    SELECT expense.id
    FROM expenses expense
    LEFT JOIN legacy_transaction_map legacy_map
      ON legacy_map.legacy_table = 'EXPENSES'
     AND legacy_map.legacy_id = expense.id
    WHERE legacy_map.transaction_id IS NULL
) unmapped_legacy_row;

SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM (
    SELECT income.id
    FROM incomes income
    JOIN legacy_transaction_map legacy_map
      ON legacy_map.legacy_table = 'INCOMES'
     AND legacy_map.legacy_id = income.id
    WHERE legacy_map.legacy_expense_category IS NOT NULL
    UNION ALL
    SELECT expense.id
    FROM expenses expense
    JOIN legacy_transaction_map legacy_map
      ON legacy_map.legacy_table = 'EXPENSES'
     AND legacy_map.legacy_id = expense.id
    WHERE legacy_map.legacy_expense_category IS DISTINCT FROM expense.category
) changed_legacy_expense_category;

SELECT 1 / CASE WHEN
    (SELECT COUNT(*) FROM transaction_import_references)
        = (
            SELECT COUNT(*)
            FROM incomes
            WHERE source_type IS NOT NULL OR source_id IS NOT NULL OR source IS NOT NULL
        ) + (
            SELECT COUNT(*)
            FROM expenses
            WHERE source_type IS NOT NULL OR source_id IS NOT NULL
        )
    AND (SELECT COUNT(*) FROM transaction_attachments)
        = (
            SELECT COUNT(*)
            FROM incomes
            WHERE receipt_one_drive_id IS NOT NULL OR receipt_file_name IS NOT NULL
        ) + (
            SELECT COUNT(*)
            FROM expenses
            WHERE receipt_one_drive_id IS NOT NULL OR receipt_file_name IS NOT NULL
        )
THEN 1 ELSE 0 END;

SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM financial_transactions transaction
JOIN neutral_categories category ON category.id = transaction.neutral_category_id
WHERE category.direction <> transaction.direction
   OR CHAR_LENGTH(transaction.description) = 0;

ALTER TABLE financial_transactions DROP CONSTRAINT uk_financial_transactions_migration_source;
ALTER TABLE financial_transactions DROP COLUMN migration_legacy_table;
ALTER TABLE financial_transactions DROP COLUMN migration_legacy_id;

CREATE INDEX idx_financial_transactions_date
    ON financial_transactions(transaction_date DESC);
CREATE INDEX idx_financial_transactions_direction_date
    ON financial_transactions(direction, transaction_date DESC);
CREATE INDEX idx_financial_transactions_activity
    ON financial_transactions(activity_id);
CREATE INDEX idx_financial_transactions_category
    ON financial_transactions(neutral_category_id);
CREATE INDEX idx_financial_transactions_counterparty
    ON financial_transactions(counterparty_id);
CREATE INDEX idx_transaction_attachments_transaction
    ON transaction_attachments(transaction_id);
CREATE INDEX idx_transaction_import_references_transaction
    ON transaction_import_references(transaction_id);
