-- Fail closed before copying either legacy pending table. The source preflight reported no
-- duplicate identities, but the migration independently verifies the exact database it receives.
SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM (
    SELECT normalized.origin, normalized.source_id
    FROM (
        SELECT
            COALESCE(CAST(source_type AS VARCHAR), 'MANUAL') AS origin,
            source_id
        FROM pending_expenses
        WHERE source_id IS NOT NULL
        UNION ALL
        SELECT
            COALESCE(CAST(source_type AS VARCHAR), 'MANUAL') AS origin,
            source_id
        FROM pending_incomes
        WHERE source_id IS NOT NULL
    ) normalized
    GROUP BY normalized.origin, normalized.source_id
    HAVING COUNT(*) > 1
) duplicate_pending_identity;

SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM (
    SELECT id
    FROM pending_expenses
    WHERE status IS NULL
       OR activity_id IS NULL
       OR category_id IS NULL
       OR created_at IS NULL
    UNION ALL
    SELECT id
    FROM pending_incomes
    WHERE status IS NULL
       OR activity_id IS NULL
       OR category_id IS NULL
       OR created_at IS NULL
) invalid_pending_row;

CREATE TABLE inbox_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin VARCHAR(50) NOT NULL,
    legacy_source_type VARCHAR(50),
    legacy_source_id VARCHAR(255),
    immutable_source_id VARCHAR(255),
    state VARCHAR(30) NOT NULL,
    external_sync_state VARCHAR(30) NOT NULL,
    proposed_direction VARCHAR(20),
    raw_status VARCHAR(50) NOT NULL,
    subject VARCHAR(1000),
    proposed_amount NUMERIC(38, 2),
    proposed_description VARCHAR(2000),
    proposed_date DATE,
    proposed_category VARCHAR(255),
    proposed_property_name VARCHAR(255),
    proposed_counterparty_name VARCHAR(255),
    proposed_source_label VARCHAR(500),
    legacy_activity_id BIGINT,
    legacy_category_id BIGINT,
    legacy_property_id BIGINT,
    legacy_counterparty_id BIGINT,
    configured_activity_id BIGINT,
    classification_ambiguous BOOLEAN NOT NULL,
    error_message VARCHAR(2000),
    receipt_external_id VARCHAR(255),
    receipt_file_name VARCHAR(500),
    financial_transaction_id BIGINT,
    migration_legacy_table VARCHAR(30),
    migration_legacy_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_inbox_items_origin_identity UNIQUE (origin, legacy_source_id),
    CONSTRAINT uk_inbox_items_migration_source
        UNIQUE (migration_legacy_table, migration_legacy_id),
    CONSTRAINT fk_inbox_items_financial_transaction
        FOREIGN KEY (financial_transaction_id) REFERENCES financial_transactions(id)
);

CREATE INDEX idx_inbox_items_state ON inbox_items(state);
CREATE INDEX idx_inbox_items_external_sync_state ON inbox_items(external_sync_state);
CREATE INDEX idx_inbox_items_created_at ON inbox_items(created_at);

CREATE TABLE inbox_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inbox_item_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    text_value VARCHAR(2000),
    external_id VARCHAR(255),
    file_name VARCHAR(500),
    sha256 VARCHAR(64),
    CONSTRAINT ck_inbox_artifacts_sha256
        CHECK (sha256 IS NULL OR CHAR_LENGTH(sha256) = 64),
    CONSTRAINT fk_inbox_artifacts_item
        FOREIGN KEY (inbox_item_id) REFERENCES inbox_items(id)
);

CREATE INDEX idx_inbox_artifacts_item ON inbox_artifacts(inbox_item_id);

CREATE TABLE legacy_inbox_map (
    legacy_table VARCHAR(30) NOT NULL,
    legacy_id BIGINT NOT NULL,
    inbox_item_id BIGINT NOT NULL,
    mapped_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_legacy_inbox_map PRIMARY KEY (legacy_table, legacy_id),
    CONSTRAINT fk_legacy_inbox_map_item
        FOREIGN KEY (inbox_item_id) REFERENCES inbox_items(id)
);

CREATE INDEX idx_legacy_inbox_map_item ON legacy_inbox_map(inbox_item_id);

CREATE TABLE background_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inbox_item_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    idempotency_key VARCHAR(500) NOT NULL,
    state VARCHAR(30) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    available_at TIMESTAMP(6) NOT NULL,
    lease_owner VARCHAR(255),
    lease_expires_at TIMESTAMP(6),
    last_error VARCHAR(2000),
    terminal_reason VARCHAR(100),
    legacy_pending_table VARCHAR(30),
    legacy_pending_id BIGINT,
    target_year INTEGER,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_background_jobs_idempotency UNIQUE (idempotency_key),
    CONSTRAINT ck_background_jobs_attempts
        CHECK (attempts >= 0 AND max_attempts > 0 AND attempts <= max_attempts),
    CONSTRAINT ck_background_jobs_lease
        CHECK (
            (state = 'LEASED' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
            OR state <> 'LEASED'
        ),
    CONSTRAINT fk_background_jobs_item
        FOREIGN KEY (inbox_item_id) REFERENCES inbox_items(id)
);

CREATE INDEX idx_background_jobs_claim
    ON background_jobs(state, available_at, lease_expires_at);
CREATE INDEX idx_background_jobs_item ON background_jobs(inbox_item_id);

INSERT INTO inbox_items (
    origin,
    legacy_source_type,
    legacy_source_id,
    immutable_source_id,
    state,
    external_sync_state,
    proposed_direction,
    raw_status,
    subject,
    proposed_amount,
    proposed_description,
    proposed_date,
    proposed_category,
    proposed_property_name,
    proposed_counterparty_name,
    proposed_source_label,
    legacy_activity_id,
    legacy_category_id,
    legacy_property_id,
    legacy_counterparty_id,
    configured_activity_id,
    classification_ambiguous,
    error_message,
    receipt_external_id,
    receipt_file_name,
    financial_transaction_id,
    migration_legacy_table,
    migration_legacy_id,
    created_at,
    updated_at,
    version
)
SELECT
    COALESCE(CAST(source_type AS VARCHAR), 'MANUAL'),
    CAST(source_type AS VARCHAR),
    source_id,
    NULL,
    CAST(status AS VARCHAR),
    'NOT_REQUIRED',
    CAST(email_type AS VARCHAR),
    CAST(status AS VARCHAR),
    subject,
    amount,
    description,
    date,
    category,
    property_name,
    payer_name,
    NULL,
    activity_id,
    category_id,
    NULL,
    NULL,
    configured_activity_id,
    classification_ambiguous,
    error_message,
    CASE WHEN CAST(source_type AS VARCHAR) = 'RECEIPT' THEN source_id ELSE NULL END,
    CASE WHEN CAST(source_type AS VARCHAR) = 'RECEIPT' THEN subject ELSE NULL END,
    NULL,
    'PENDING_EXPENSES',
    id,
    created_at,
    CURRENT_TIMESTAMP,
    0
FROM pending_expenses
ORDER BY id;

INSERT INTO inbox_items (
    origin,
    legacy_source_type,
    legacy_source_id,
    immutable_source_id,
    state,
    external_sync_state,
    proposed_direction,
    raw_status,
    subject,
    proposed_amount,
    proposed_description,
    proposed_date,
    proposed_category,
    proposed_property_name,
    proposed_counterparty_name,
    proposed_source_label,
    legacy_activity_id,
    legacy_category_id,
    legacy_property_id,
    legacy_counterparty_id,
    configured_activity_id,
    classification_ambiguous,
    error_message,
    receipt_external_id,
    receipt_file_name,
    financial_transaction_id,
    migration_legacy_table,
    migration_legacy_id,
    created_at,
    updated_at,
    version
)
SELECT
    COALESCE(CAST(source_type AS VARCHAR), 'MANUAL'),
    CAST(source_type AS VARCHAR),
    source_id,
    NULL,
    CAST(status AS VARCHAR),
    'NOT_REQUIRED',
    'INCOME',
    CAST(status AS VARCHAR),
    NULL,
    amount,
    description,
    date,
    NULL,
    NULL,
    NULL,
    source,
    activity_id,
    category_id,
    property_id,
    payer_id,
    NULL,
    classification_ambiguous,
    error_message,
    receipt_one_drive_id,
    receipt_file_name,
    NULL,
    'PENDING_INCOMES',
    id,
    created_at,
    CURRENT_TIMESTAMP,
    0
FROM pending_incomes
ORDER BY id;

INSERT INTO inbox_artifacts (
    inbox_item_id,
    type,
    text_value,
    external_id,
    file_name,
    sha256
)
SELECT
    item.id,
    'UNRECOGNIZED_ALIAS',
    alias.alias,
    NULL,
    NULL,
    NULL
FROM pending_expense_aliases alias
JOIN inbox_items item
  ON item.migration_legacy_table = 'PENDING_EXPENSES'
 AND item.migration_legacy_id = alias.pending_expense_id;

INSERT INTO inbox_artifacts (
    inbox_item_id,
    type,
    text_value,
    external_id,
    file_name,
    sha256
)
SELECT
    item.id,
    'RECEIPT',
    NULL,
    item.receipt_external_id,
    item.receipt_file_name,
    receipt_hash.sha256
FROM inbox_items item
LEFT JOIN receipt_hashes receipt_hash
  ON receipt_hash.drive_item_id = item.receipt_external_id
WHERE item.receipt_external_id IS NOT NULL
   OR item.receipt_file_name IS NOT NULL;

INSERT INTO legacy_inbox_map (
    legacy_table,
    legacy_id,
    inbox_item_id,
    mapped_at
)
SELECT
    migration_legacy_table,
    migration_legacy_id,
    id,
    CURRENT_TIMESTAMP
FROM inbox_items;

-- PROCESSING legacy rows become recoverable parse jobs. No external call is made by migration;
-- the worker is disabled by default and only leases these rows after an explicit runtime enable.
INSERT INTO background_jobs (
    inbox_item_id,
    type,
    idempotency_key,
    state,
    attempts,
    max_attempts,
    available_at,
    lease_owner,
    lease_expires_at,
    last_error,
    terminal_reason,
    legacy_pending_table,
    legacy_pending_id,
    target_year,
    created_at,
    updated_at,
    version
)
SELECT
    item.id,
    CASE
        WHEN item.origin = 'OUTLOOK_EMAIL' THEN 'PARSE_OUTLOOK'
        ELSE 'PARSE_RECEIPT'
    END,
    LOWER(
        CASE
            WHEN item.origin = 'OUTLOOK_EMAIL' THEN 'PARSE_OUTLOOK'
            ELSE 'PARSE_RECEIPT'
        END
    ) || ':' || CAST(item.id AS VARCHAR),
    'AVAILABLE',
    0,
    5,
    CURRENT_TIMESTAMP,
    NULL,
    NULL,
    NULL,
    NULL,
    item.migration_legacy_table,
    item.migration_legacy_id,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
FROM inbox_items item
WHERE item.migration_legacy_table = 'PENDING_EXPENSES'
  AND item.state = 'PROCESSING'
  AND item.origin IN ('OUTLOOK_EMAIL', 'RECEIPT');

-- Existing mutable Outlook IDs are retained and translated later by a durable, visible job.
INSERT INTO background_jobs (
    inbox_item_id,
    type,
    idempotency_key,
    state,
    attempts,
    max_attempts,
    available_at,
    lease_owner,
    lease_expires_at,
    last_error,
    terminal_reason,
    legacy_pending_table,
    legacy_pending_id,
    target_year,
    created_at,
    updated_at,
    version
)
SELECT
    item.id,
    'TRANSLATE_OUTLOOK_ID',
    'translate_outlook_id:' || CAST(item.id AS VARCHAR),
    'AVAILABLE',
    0,
    5,
    CURRENT_TIMESTAMP,
    NULL,
    NULL,
    NULL,
    NULL,
    item.migration_legacy_table,
    item.migration_legacy_id,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
FROM inbox_items item
WHERE item.origin = 'OUTLOOK_EMAIL'
  AND item.legacy_source_id IS NOT NULL;

-- Every source row remains byte-semantically untouched and has exactly one durable mapping.
SELECT 1 / CASE WHEN
    (SELECT COUNT(*) FROM inbox_items)
        = (SELECT COUNT(*) FROM pending_expenses) + (SELECT COUNT(*) FROM pending_incomes)
    AND (SELECT COUNT(*) FROM legacy_inbox_map)
        = (SELECT COUNT(*) FROM pending_expenses) + (SELECT COUNT(*) FROM pending_incomes)
    AND (
        SELECT COUNT(*)
        FROM inbox_artifacts
        WHERE type = 'UNRECOGNIZED_ALIAS'
    ) = (SELECT COUNT(*) FROM pending_expense_aliases)
THEN 1 ELSE 0 END;

SELECT 1 / CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END
FROM (
    SELECT pending.id
    FROM pending_expenses pending
    JOIN inbox_items item
      ON item.migration_legacy_table = 'PENDING_EXPENSES'
     AND item.migration_legacy_id = pending.id
    WHERE item.legacy_source_type IS DISTINCT FROM CAST(pending.source_type AS VARCHAR)
       OR item.legacy_source_id IS DISTINCT FROM pending.source_id
       OR item.raw_status IS DISTINCT FROM CAST(pending.status AS VARCHAR)
       OR item.subject IS DISTINCT FROM pending.subject
       OR item.proposed_amount IS DISTINCT FROM pending.amount
       OR item.proposed_description IS DISTINCT FROM pending.description
       OR item.proposed_date IS DISTINCT FROM pending.date
       OR item.proposed_category IS DISTINCT FROM pending.category
       OR item.proposed_property_name IS DISTINCT FROM pending.property_name
       OR item.proposed_counterparty_name IS DISTINCT FROM pending.payer_name
       OR item.legacy_activity_id IS DISTINCT FROM pending.activity_id
       OR item.legacy_category_id IS DISTINCT FROM pending.category_id
       OR item.configured_activity_id IS DISTINCT FROM pending.configured_activity_id
       OR item.classification_ambiguous IS DISTINCT FROM pending.classification_ambiguous
       OR item.error_message IS DISTINCT FROM pending.error_message
       OR item.created_at IS DISTINCT FROM pending.created_at
    UNION ALL
    SELECT pending.id
    FROM pending_incomes pending
    JOIN inbox_items item
      ON item.migration_legacy_table = 'PENDING_INCOMES'
     AND item.migration_legacy_id = pending.id
    WHERE item.legacy_source_type IS DISTINCT FROM CAST(pending.source_type AS VARCHAR)
       OR item.legacy_source_id IS DISTINCT FROM pending.source_id
       OR item.raw_status IS DISTINCT FROM CAST(pending.status AS VARCHAR)
       OR item.proposed_amount IS DISTINCT FROM pending.amount
       OR item.proposed_description IS DISTINCT FROM pending.description
       OR item.proposed_date IS DISTINCT FROM pending.date
       OR item.proposed_source_label IS DISTINCT FROM pending.source
       OR item.legacy_activity_id IS DISTINCT FROM pending.activity_id
       OR item.legacy_category_id IS DISTINCT FROM pending.category_id
       OR item.legacy_property_id IS DISTINCT FROM pending.property_id
       OR item.legacy_counterparty_id IS DISTINCT FROM pending.payer_id
       OR item.classification_ambiguous IS DISTINCT FROM pending.classification_ambiguous
       OR item.error_message IS DISTINCT FROM pending.error_message
       OR item.receipt_external_id IS DISTINCT FROM pending.receipt_one_drive_id
       OR item.receipt_file_name IS DISTINCT FROM pending.receipt_file_name
       OR item.created_at IS DISTINCT FROM pending.created_at
) changed_or_missing_pending_row;
