CREATE TABLE household_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    system_key VARCHAR(100),
    CONSTRAINT uk_household_members_name UNIQUE (name),
    CONSTRAINT uk_household_members_system_key UNIQUE (system_key)
);

INSERT INTO household_members (name, active, system_key)
VALUES ('Household', TRUE, 'DEFAULT_HOUSEHOLD');

CREATE TABLE financial_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    activity_type VARCHAR(50) NOT NULL,
    tax_treatment VARCHAR(50) NOT NULL,
    owner_id BIGINT NOT NULL,
    property_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    system_key VARCHAR(100),
    CONSTRAINT uk_financial_activities_name UNIQUE (name),
    CONSTRAINT uk_financial_activities_property UNIQUE (property_id),
    CONSTRAINT uk_financial_activities_system_key UNIQUE (system_key),
    CONSTRAINT fk_financial_activities_owner
        FOREIGN KEY (owner_id) REFERENCES household_members(id),
    CONSTRAINT fk_financial_activities_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
);

INSERT INTO financial_activities
    (name, activity_type, tax_treatment, owner_id, property_id, active)
SELECT
    CASE
        WHEN LOWER(p.name) = 'needs classification' OR (
            SELECT COUNT(*)
            FROM properties duplicate_property
            WHERE LOWER(duplicate_property.name) = LOWER(p.name)
        ) > 1
        THEN p.name || ' (' || p.id || ')'
        ELSE p.name
    END,
    'RENTAL',
    'SCHEDULE_E',
    (SELECT MIN(id) FROM household_members),
    p.id,
    TRUE
FROM properties p;

INSERT INTO financial_activities
    (name, activity_type, tax_treatment, owner_id, property_id, active, system_key)
VALUES
    (
        'Needs classification',
        'OTHER',
        'NONE',
        (SELECT MIN(id) FROM household_members),
        NULL,
        TRUE,
        'NEEDS_CLASSIFICATION'
    );

ALTER TABLE incomes ADD COLUMN activity_id BIGINT;
ALTER TABLE expenses ADD COLUMN activity_id BIGINT;
ALTER TABLE pending_incomes ADD COLUMN activity_id BIGINT;
ALTER TABLE pending_expenses ADD COLUMN activity_id BIGINT;

UPDATE incomes i
SET activity_id = (
    SELECT fa.id
    FROM financial_activities fa
    WHERE fa.property_id = i.property_id
)
WHERE i.property_id IS NOT NULL;

UPDATE expenses e
SET activity_id = (
    SELECT fa.id
    FROM financial_activities fa
    WHERE fa.property_id = e.property_id
)
WHERE e.property_id IS NOT NULL;

UPDATE pending_incomes pi
SET activity_id = (
    SELECT fa.id
    FROM financial_activities fa
    WHERE fa.property_id = pi.property_id
)
WHERE pi.property_id IS NOT NULL;

UPDATE pending_expenses pe
SET activity_id = (
    SELECT MIN(fa.id)
    FROM financial_activities fa
    JOIN properties p ON p.id = fa.property_id
    WHERE LOWER(p.name) = LOWER(pe.property_name)
)
WHERE pe.property_name IS NOT NULL;

UPDATE incomes
SET activity_id = (
    SELECT id FROM financial_activities WHERE system_key = 'NEEDS_CLASSIFICATION'
)
WHERE activity_id IS NULL;

UPDATE expenses
SET activity_id = (
    SELECT id FROM financial_activities WHERE system_key = 'NEEDS_CLASSIFICATION'
)
WHERE activity_id IS NULL;

UPDATE pending_incomes
SET activity_id = (
    SELECT id FROM financial_activities WHERE system_key = 'NEEDS_CLASSIFICATION'
)
WHERE activity_id IS NULL;

UPDATE pending_expenses
SET activity_id = (
    SELECT id FROM financial_activities WHERE system_key = 'NEEDS_CLASSIFICATION'
)
WHERE activity_id IS NULL;

ALTER TABLE incomes ALTER COLUMN activity_id SET NOT NULL;
ALTER TABLE expenses ALTER COLUMN activity_id SET NOT NULL;
ALTER TABLE pending_incomes ALTER COLUMN activity_id SET NOT NULL;
ALTER TABLE pending_expenses ALTER COLUMN activity_id SET NOT NULL;

ALTER TABLE incomes
    ADD CONSTRAINT fk_incomes_activity
    FOREIGN KEY (activity_id) REFERENCES financial_activities(id);
ALTER TABLE expenses
    ADD CONSTRAINT fk_expenses_activity
    FOREIGN KEY (activity_id) REFERENCES financial_activities(id);
ALTER TABLE pending_incomes
    ADD CONSTRAINT fk_pending_incomes_activity
    FOREIGN KEY (activity_id) REFERENCES financial_activities(id);
ALTER TABLE pending_expenses
    ADD CONSTRAINT fk_pending_expenses_activity
    FOREIGN KEY (activity_id) REFERENCES financial_activities(id);

CREATE INDEX idx_incomes_activity ON incomes(activity_id);
CREATE INDEX idx_expenses_activity ON expenses(activity_id);
CREATE INDEX idx_pending_incomes_activity ON pending_incomes(activity_id);
CREATE INDEX idx_pending_expenses_activity ON pending_expenses(activity_id);
