CREATE TABLE financial_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_key VARCHAR(100) NOT NULL,
    label VARCHAR(255) NOT NULL,
    direction VARCHAR(20) NOT NULL,
    tax_treatment VARCHAR(50) NOT NULL,
    tax_line VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    system BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_financial_categories_key UNIQUE (category_key)
);

INSERT INTO financial_categories
    (category_key, label, direction, tax_treatment, tax_line, active, system)
VALUES
    ('RENTAL_INCOME', 'Rental Income', 'INCOME', 'SCHEDULE_E', 'Rents received', TRUE, TRUE),
    ('ADVERTISING', 'Advertising', 'EXPENSE', 'SCHEDULE_E', '5', TRUE, TRUE),
    ('AUTO_AND_TRAVEL', 'Auto and travel', 'EXPENSE', 'SCHEDULE_E', '6', TRUE, TRUE),
    ('CLEANING_AND_MAINTENANCE', 'Cleaning and maintenance', 'EXPENSE', 'SCHEDULE_E', '7', TRUE, TRUE),
    ('COMMISSIONS', 'Commissions', 'EXPENSE', 'SCHEDULE_E', '8', TRUE, TRUE),
    ('INSURANCE', 'Insurance', 'EXPENSE', 'SCHEDULE_E', '9', TRUE, TRUE),
    ('LEGAL_AND_PROFESSIONAL', 'Legal and professional fees', 'EXPENSE', 'SCHEDULE_E', '10', TRUE, TRUE),
    ('MANAGEMENT_FEES', 'Management fees', 'EXPENSE', 'SCHEDULE_E', '11', TRUE, TRUE),
    ('MORTGAGE_INTEREST', 'Mortgage interest', 'EXPENSE', 'SCHEDULE_E', '12', TRUE, TRUE),
    ('OTHER_INTEREST', 'Other interest', 'EXPENSE', 'SCHEDULE_E', '13', TRUE, TRUE),
    ('REPAIRS', 'Repairs', 'EXPENSE', 'SCHEDULE_E', '14', TRUE, TRUE),
    ('SUPPLIES', 'Supplies', 'EXPENSE', 'SCHEDULE_E', '15', TRUE, TRUE),
    ('TAXES', 'Taxes', 'EXPENSE', 'SCHEDULE_E', '16', TRUE, TRUE),
    ('UTILITIES', 'Utilities', 'EXPENSE', 'SCHEDULE_E', '17', TRUE, TRUE),
    ('DEPRECIATION', 'Depreciation', 'EXPENSE', 'SCHEDULE_E', '18', TRUE, TRUE),
    ('OTHER', 'Other', 'EXPENSE', 'SCHEDULE_E', '19', TRUE, TRUE),
    ('WAGES', 'Wages', 'INCOME', 'W2', NULL, TRUE, TRUE),
    ('REIMBURSEMENT', 'Reimbursement', 'INCOME', 'W2', NULL, TRUE, TRUE),
    ('EDUCATOR_EXPENSE', 'Educator Expense', 'EXPENSE', 'W2', 'Schedule 1 educator expense', TRUE, TRUE),
    ('EMPLOYMENT_OTHER_EXPENSE', 'Other employment expense', 'EXPENSE', 'W2', NULL, TRUE, TRUE),
    ('SERVICE_INCOME', 'Service Income', 'INCOME', 'SCHEDULE_C', NULL, TRUE, TRUE),
    ('SCHEDULE_C_ADVERTISING', 'Advertising', 'EXPENSE', 'SCHEDULE_C', NULL, TRUE, TRUE),
    ('SCHEDULE_C_CAR_AND_TRUCK', 'Car and truck expense', 'EXPENSE', 'SCHEDULE_C', NULL, TRUE, TRUE),
    ('SCHEDULE_C_CONTRACT_LABOR', 'Contract labor', 'EXPENSE', 'SCHEDULE_C', NULL, TRUE, TRUE),
    ('SCHEDULE_C_INSURANCE', 'Insurance', 'EXPENSE', 'SCHEDULE_C', NULL, TRUE, TRUE),
    ('SCHEDULE_C_LEGAL_AND_PROFESSIONAL', 'Legal and professional services', 'EXPENSE', 'SCHEDULE_C', NULL, TRUE, TRUE),
    ('SCHEDULE_C_OFFICE_EXPENSE', 'Office expense', 'EXPENSE', 'SCHEDULE_C', NULL, TRUE, TRUE),
    ('SCHEDULE_C_REPAIRS', 'Repairs and maintenance', 'EXPENSE', 'SCHEDULE_C', NULL, TRUE, TRUE),
    ('SCHEDULE_C_SUPPLIES', 'Supplies', 'EXPENSE', 'SCHEDULE_C', NULL, TRUE, TRUE),
    ('SCHEDULE_C_UTILITIES', 'Utilities', 'EXPENSE', 'SCHEDULE_C', NULL, TRUE, TRUE),
    ('SCHEDULE_C_OTHER_EXPENSE', 'Other business expense', 'EXPENSE', 'SCHEDULE_C', NULL, TRUE, TRUE),
    ('OTHER_INCOME', 'Other Income', 'INCOME', 'NONE', NULL, TRUE, TRUE),
    ('OTHER_REIMBURSEMENT', 'Reimbursement', 'INCOME', 'NONE', NULL, TRUE, TRUE),
    ('OTHER_EXPENSE', 'Other Expense', 'EXPENSE', 'NONE', NULL, TRUE, TRUE);

ALTER TABLE incomes ADD COLUMN category_id BIGINT;
ALTER TABLE expenses ADD COLUMN category_id BIGINT;
ALTER TABLE pending_incomes ADD COLUMN category_id BIGINT;
ALTER TABLE pending_expenses ADD COLUMN category_id BIGINT;

UPDATE incomes i
SET category_id = (
    SELECT fc.id
    FROM financial_categories fc
    WHERE fc.category_key = CASE
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = i.activity_id
        ) = 'SCHEDULE_E' THEN 'RENTAL_INCOME'
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = i.activity_id
        ) = 'W2' THEN 'WAGES'
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = i.activity_id
        ) = 'SCHEDULE_C' THEN 'SERVICE_INCOME'
        ELSE 'OTHER_INCOME'
    END
);

UPDATE expenses e
SET category_id = (
    SELECT fc.id
    FROM financial_categories fc
    WHERE fc.category_key = CASE
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = e.activity_id
        ) = 'SCHEDULE_E' THEN COALESCE(CAST(e.category AS VARCHAR), 'OTHER')
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = e.activity_id
        ) = 'W2' THEN 'EMPLOYMENT_OTHER_EXPENSE'
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = e.activity_id
        ) = 'SCHEDULE_C' THEN 'SCHEDULE_C_OTHER_EXPENSE'
        ELSE 'OTHER_EXPENSE'
    END
);

UPDATE expenses
SET category_id = (SELECT id FROM financial_categories WHERE category_key = 'OTHER_EXPENSE')
WHERE category_id IS NULL;

UPDATE pending_incomes pi
SET category_id = (
    SELECT fc.id
    FROM financial_categories fc
    WHERE fc.category_key = CASE
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = pi.activity_id
        ) = 'SCHEDULE_E' THEN 'RENTAL_INCOME'
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = pi.activity_id
        ) = 'W2' THEN 'WAGES'
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = pi.activity_id
        ) = 'SCHEDULE_C' THEN 'SERVICE_INCOME'
        ELSE 'OTHER_INCOME'
    END
);

UPDATE pending_expenses pe
SET category_id = (
    SELECT fc.id
    FROM financial_categories fc
    WHERE fc.category_key = CASE
        WHEN pe.email_type = 'INCOME' AND (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = pe.activity_id
        ) = 'SCHEDULE_E' THEN 'RENTAL_INCOME'
        WHEN pe.email_type = 'INCOME' AND (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = pe.activity_id
        ) = 'W2' THEN 'WAGES'
        WHEN pe.email_type = 'INCOME' AND (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = pe.activity_id
        ) = 'SCHEDULE_C' THEN 'SERVICE_INCOME'
        WHEN pe.email_type = 'INCOME' THEN 'OTHER_INCOME'
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = pe.activity_id
        ) = 'SCHEDULE_E' AND EXISTS (
            SELECT 1
            FROM financial_categories suggested
            WHERE suggested.category_key = pe.category
              AND suggested.direction = 'EXPENSE'
              AND suggested.tax_treatment = 'SCHEDULE_E'
        ) THEN pe.category
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = pe.activity_id
        ) = 'SCHEDULE_E' THEN 'OTHER'
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = pe.activity_id
        ) = 'W2' THEN 'EMPLOYMENT_OTHER_EXPENSE'
        WHEN (
            SELECT fa.tax_treatment
            FROM financial_activities fa
            WHERE fa.id = pe.activity_id
        ) = 'SCHEDULE_C' THEN 'SCHEDULE_C_OTHER_EXPENSE'
        ELSE 'OTHER_EXPENSE'
    END
);

UPDATE pending_expenses pe
SET category_id = (
    SELECT id
    FROM financial_categories
    WHERE category_key = CASE
        WHEN pe.email_type = 'INCOME' THEN 'OTHER_INCOME'
        ELSE 'OTHER_EXPENSE'
    END
)
WHERE category_id IS NULL;

ALTER TABLE incomes ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE expenses ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE pending_incomes ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE pending_expenses ALTER COLUMN category_id SET NOT NULL;

ALTER TABLE incomes
    ADD CONSTRAINT fk_incomes_financial_category
    FOREIGN KEY (category_id) REFERENCES financial_categories(id);
ALTER TABLE expenses
    ADD CONSTRAINT fk_expenses_financial_category
    FOREIGN KEY (category_id) REFERENCES financial_categories(id);
ALTER TABLE pending_incomes
    ADD CONSTRAINT fk_pending_incomes_financial_category
    FOREIGN KEY (category_id) REFERENCES financial_categories(id);
ALTER TABLE pending_expenses
    ADD CONSTRAINT fk_pending_expenses_financial_category
    FOREIGN KEY (category_id) REFERENCES financial_categories(id);

CREATE INDEX idx_incomes_category ON incomes(category_id);
CREATE INDEX idx_expenses_category ON expenses(category_id);
CREATE INDEX idx_pending_incomes_category ON pending_incomes(category_id);
CREATE INDEX idx_pending_expenses_category ON pending_expenses(category_id);
