ALTER TABLE outlook_settings_folder ADD COLUMN activity_id BIGINT;
ALTER TABLE outlook_settings_folder
    ADD CONSTRAINT fk_outlook_settings_folder_activity
    FOREIGN KEY (activity_id) REFERENCES financial_activities(id) ON DELETE SET NULL;

ALTER TABLE pending_expenses ADD COLUMN configured_activity_id BIGINT;
ALTER TABLE pending_expenses ADD COLUMN classification_ambiguous BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE pending_expenses
    ADD CONSTRAINT fk_pending_expenses_configured_activity
    FOREIGN KEY (configured_activity_id) REFERENCES financial_activities(id) ON DELETE SET NULL;

ALTER TABLE pending_incomes ADD COLUMN classification_ambiguous BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE email_keyword_classification_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(255) NOT NULL,
    activity_id BIGINT NOT NULL,
    financial_category_id BIGINT NOT NULL,
    occurrences INTEGER NOT NULL,
    version BIGINT,
    CONSTRAINT uk_email_keyword_classification
        UNIQUE (keyword, activity_id, financial_category_id),
    CONSTRAINT fk_email_keyword_classification_activity
        FOREIGN KEY (activity_id) REFERENCES financial_activities(id) ON DELETE CASCADE,
    CONSTRAINT fk_email_keyword_classification_category
        FOREIGN KEY (financial_category_id) REFERENCES financial_categories(id) ON DELETE CASCADE
);

CREATE INDEX idx_email_keyword_classification_keyword
    ON email_keyword_classification_history(keyword);
CREATE INDEX idx_email_keyword_classification_activity
    ON email_keyword_classification_history(activity_id);
