export const queryKeys = {
  pendingExpenses: ['pendingExpenses'],
  expenses: ['expenses'],
  incomes: ['incomes'],
  totalExpenses: ['totalExpenses'],
  totalIncome: ['totalIncome'],
  expenseCategories: ['expenseCategories'],
  properties: ['properties'],
  payers: ['payers'],
  propertyTypes: ['propertyTypes'],
  payerTypes: ['payerTypes'],
  receiptSettings: ['receiptSettings'],
  receipts: ['receipts'],
  reconciliation: ['reconciliation'],
  backups: ['backups'],
  outlookStatus: ['outlookStatus'],
  outlookRentalEmails: (page, refreshKey) => ['outlookRentalEmails', page, refreshKey],
  outlookAvailableFolders: ['outlookAvailableFolders'],
  outlookFolderSettings: ['outlookFolderSettings'],
  outlookMoveSettings: ['outlookMoveSettings'],
};
