export const queryKeys = {
  pendingExpenses: ['pendingExpenses'],
  pendingIncomes: ['pendingIncomes'],
  expenses: ['expenses'],
  incomes: ['incomes'],
  totalExpenses: ['totalExpenses'],
  totalIncome: ['totalIncome'],
  expenseCategories: ['expenseCategories'],
  categories: ['categories'],
  financialActivities: ['financialActivities'],
  financialActivityTypes: ['financialActivityTypes'],
  taxTreatments: ['taxTreatments'],
  householdMembers: ['householdMembers'],
  financialCategories: (direction, activityId) => [
    'financialCategories',
    direction,
    activityId ?? null,
  ],
  cashflowReport: (from, to, ownerId, activityId) => [
    'reports',
    'cashflow',
    from,
    to,
    ownerId ?? null,
    activityId ?? null,
  ],
  scheduleEReport: (year, ownerId, activityId) => [
    'reports',
    'scheduleE',
    year,
    ownerId ?? null,
    activityId ?? null,
  ],
  properties: ['properties'],
  propertyKeywords: ['propertyKeywords'],
  payers: ['payers'],
  payerKeywords: ['payerKeywords'],
  propertyTypes: ['propertyTypes'],
  payerTypes: ['payerTypes'],
  receiptSettings: ['receiptSettings'],
  receipts: ['receipts'],
  receiptContent: (itemId) => ['receipts', itemId, 'content'],
  reconciliation: ['reconciliation'],
  backups: ['backups'],
  outlookStatus: ['outlookStatus'],
  outlookEmailContent: (sourceId) => ['outlookEmailContent', sourceId],
  outlookRentalEmails: (page, refreshKey) => ['outlookRentalEmails', page, refreshKey],
  outlookAvailableFolders: ['outlookAvailableFolders'],
  outlookFolderSettings: ['outlookFolderSettings'],
  outlookMoveSettings: ['outlookMoveSettings'],
};
