-- Initial schema baselined from the live Hibernate ddl-auto=update database.
-- Existing installations skip this script via spring.flyway.baseline-on-migrate=true at baseline-version=1.
-- Fresh installations run it to create all tables matching the JPA entity model.

CREATE TABLE properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    notes VARCHAR(255),
    type ENUM('COMMERCIAL', 'CONDO', 'MULTI_FAMILY', 'OTHER', 'SINGLE_FAMILY', 'TOWNHOUSE')
);

CREATE TABLE property_accounts (
    property_id BIGINT NOT NULL,
    account_number VARCHAR(255) NOT NULL,
    CONSTRAINT fk_property_accounts_property FOREIGN KEY (property_id) REFERENCES properties(id)
);

CREATE TABLE payers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type ENUM('COMPANY', 'PERSON')
);

CREATE TABLE payer_accounts (
    payer_id BIGINT NOT NULL,
    account_number VARCHAR(255) NOT NULL,
    CONSTRAINT fk_payer_accounts_payer FOREIGN KEY (payer_id) REFERENCES payers(id)
);

CREATE TABLE payer_aliases (
    payer_id BIGINT NOT NULL,
    alias VARCHAR(255) NOT NULL,
    CONSTRAINT fk_payer_aliases_payer FOREIGN KEY (payer_id) REFERENCES payers(id)
);

CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(38, 2) NOT NULL,
    category ENUM('ADVERTISING', 'AUTO_AND_TRAVEL', 'CLEANING_AND_MAINTENANCE', 'COMMISSIONS', 'DEPRECIATION', 'INSURANCE', 'LEGAL_AND_PROFESSIONAL', 'MANAGEMENT_FEES', 'MORTGAGE_INTEREST', 'OTHER', 'OTHER_INTEREST', 'REPAIRS', 'SUPPLIES', 'TAXES', 'UTILITIES'),
    date DATE NOT NULL,
    description VARCHAR(255) NOT NULL,
    source_id VARCHAR(255),
    source_type VARCHAR(255),
    payer_id BIGINT,
    property_id BIGINT,
    receipt_file_name VARCHAR(255),
    receipt_one_drive_id VARCHAR(255),
    CONSTRAINT fk_expenses_payer FOREIGN KEY (payer_id) REFERENCES payers(id),
    CONSTRAINT fk_expenses_property FOREIGN KEY (property_id) REFERENCES properties(id)
);

CREATE TABLE incomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(38, 2) NOT NULL,
    date DATE NOT NULL,
    description VARCHAR(255) NOT NULL,
    source VARCHAR(255),
    property_id BIGINT,
    source_id VARCHAR(255),
    source_type ENUM('MANUAL', 'OUTLOOK_EMAIL'),
    receipt_file_name VARCHAR(255),
    receipt_one_drive_id VARCHAR(255),
    CONSTRAINT fk_incomes_property FOREIGN KEY (property_id) REFERENCES properties(id)
);

CREATE TABLE payer_property_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrences INTEGER NOT NULL,
    payer_id BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    version BIGINT,
    CONSTRAINT uk_payer_property_history UNIQUE (payer_id, property_id),
    CONSTRAINT fk_pph_payer FOREIGN KEY (payer_id) REFERENCES payers(id),
    CONSTRAINT fk_pph_property FOREIGN KEY (property_id) REFERENCES properties(id)
);

CREATE TABLE payer_category_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category ENUM('ADVERTISING', 'AUTO_AND_TRAVEL', 'CLEANING_AND_MAINTENANCE', 'COMMISSIONS', 'DEPRECIATION', 'INSURANCE', 'LEGAL_AND_PROFESSIONAL', 'MANAGEMENT_FEES', 'MORTGAGE_INTEREST', 'OTHER', 'OTHER_INTEREST', 'REPAIRS', 'SUPPLIES', 'TAXES', 'UTILITIES') NOT NULL,
    occurrences INTEGER NOT NULL,
    payer_id BIGINT NOT NULL,
    version BIGINT,
    CONSTRAINT uk_payer_category_history UNIQUE (payer_id, category),
    CONSTRAINT fk_pch_payer FOREIGN KEY (payer_id) REFERENCES payers(id)
);

CREATE TABLE email_keyword_property_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(255) NOT NULL,
    occurrences INTEGER NOT NULL,
    property_id BIGINT NOT NULL,
    version BIGINT,
    CONSTRAINT uk_ekph_keyword_property UNIQUE (keyword, property_id),
    CONSTRAINT fk_ekph_property FOREIGN KEY (property_id) REFERENCES properties(id)
);

CREATE TABLE email_keyword_payer_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(255) NOT NULL,
    occurrences INTEGER NOT NULL,
    payer_id BIGINT NOT NULL,
    version BIGINT,
    CONSTRAINT uk_ekpayh_keyword_payer UNIQUE (keyword, payer_id),
    CONSTRAINT fk_ekpayh_payer FOREIGN KEY (payer_id) REFERENCES payers(id)
);

CREATE TABLE email_keyword_category_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category ENUM('ADVERTISING', 'AUTO_AND_TRAVEL', 'CLEANING_AND_MAINTENANCE', 'COMMISSIONS', 'DEPRECIATION', 'INSURANCE', 'LEGAL_AND_PROFESSIONAL', 'MANAGEMENT_FEES', 'MORTGAGE_INTEREST', 'OTHER', 'OTHER_INTEREST', 'REPAIRS', 'SUPPLIES', 'TAXES', 'UTILITIES') NOT NULL,
    keyword VARCHAR(255) NOT NULL,
    occurrences INTEGER NOT NULL,
    version BIGINT,
    CONSTRAINT uk_ekch_keyword_category UNIQUE (keyword, category)
);

CREATE TABLE parsed_email_keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(255) NOT NULL,
    source_id VARCHAR(255) NOT NULL,
    CONSTRAINT uk_parsed_email_keywords UNIQUE (source_id, keyword)
);

CREATE TABLE pending_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(38, 2),
    category VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    date DATE,
    description VARCHAR(255),
    error_message VARCHAR(2000),
    payer_name VARCHAR(255),
    property_name VARCHAR(255),
    source_id VARCHAR(255),
    source_type VARCHAR(255),
    status ENUM('FAILED', 'PROCESSING', 'READY') NOT NULL,
    subject VARCHAR(255),
    email_type ENUM('EXPENSE', 'INCOME'),
    CONSTRAINT uk_pending_expenses_source_id UNIQUE (source_id)
);

CREATE TABLE pending_expense_aliases (
    pending_expense_id BIGINT NOT NULL,
    alias VARCHAR(255),
    CONSTRAINT fk_pea_pending_expense FOREIGN KEY (pending_expense_id) REFERENCES pending_expenses(id)
);

CREATE TABLE outlook_tokens (
    id BIGINT PRIMARY KEY,
    cache_data VARCHAR
);

CREATE TABLE outlook_settings (
    id BIGINT PRIMARY KEY,
    receipts_folder_base VARCHAR(255),
    move_destination_folder_id VARCHAR(255),
    auto_move_enabled BOOLEAN DEFAULT FALSE
);

CREATE TABLE outlook_settings_folder (
    settings_id BIGINT NOT NULL,
    expand_subfolders BOOLEAN,
    folder_id VARCHAR(255),
    CONSTRAINT fk_osf_settings FOREIGN KEY (settings_id) REFERENCES outlook_settings(id)
);

CREATE TABLE receipt_hashes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drive_item_id VARCHAR(255) NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    uploaded_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_receipt_hashes_sha256 UNIQUE (sha256)
);
